apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-3-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-3-nginx
  template:
    metadata:
      labels:
        app: example-3-nginx
    spec:
      containers:
      - name: example-3-nginx
        image: nginx:stable
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: shared-data
        hostPath:
          path: /home/baikja/html  # 경로  변경 필요 
          type: Directory
