apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-3-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-3-nginx
  template:
    metadata:
      labels:
        app: example-3-nginx
    spec:
      containers:
      - name: example-3-nginx
        image: nginx:stable
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        volumes:
        - name: web-content
          hostPath:
            type: Directory
            path: /home/baikja/html
